module RuboCop
  module Cop
    module Layout
      def self.autoload_cop(const_name, path, department = :Layout)
        autoload const_name, path

        RuboCop::Cop::Registry.global.autoload("#{department}/#{const_name}", "#{name}::#{const_name}")
      end

      autoload_cop :AccessModifierIndentation, 'rubocop/cop/layout/access_modifier_indentation'
      autoload_cop :ArgumentAlignment, 'rubocop/cop/layout/argument_alignment'
      autoload_cop :ArrayAlignment, 'rubocop/cop/layout/array_alignment'
      autoload_cop :AssignmentIndentation, 'rubocop/cop/layout/assignment_indentation'
      autoload_cop :BeginEndAlignment, 'rubocop/cop/layout/begin_end_alignment'
      autoload_cop :BlockAlignment, 'rubocop/cop/layout/block_alignment'
      autoload_cop :BlockEndNewline, 'rubocop/cop/layout/block_end_newline'
      autoload_cop :CaseIndentation, 'rubocop/cop/layout/case_indentation'
      autoload_cop :ClassStructure, 'rubocop/cop/layout/class_structure'
      autoload_cop :ClosingHeredocIndentation, 'rubocop/cop/layout/closing_heredoc_indentation'
      autoload_cop :ClosingParenthesisIndentation, 'rubocop/cop/layout/closing_parenthesis_indentation'
      autoload_cop :CommentIndentation, 'rubocop/cop/layout/comment_indentation'
      autoload_cop :ConditionPosition, 'rubocop/cop/layout/condition_position'
      autoload_cop :DefEndAlignment, 'rubocop/cop/layout/def_end_alignment'
      autoload_cop :DotPosition, 'rubocop/cop/layout/dot_position'
      autoload_cop :ElseAlignment, 'rubocop/cop/layout/else_alignment'
      autoload_cop :EmptyComment, 'rubocop/cop/layout/empty_comment'
      autoload_cop :EmptyLineAfterGuardClause, 'rubocop/cop/layout/empty_line_after_guard_clause'
      autoload_cop :EmptyLineAfterMagicComment, 'rubocop/cop/layout/empty_line_after_magic_comment'
      autoload_cop :EmptyLineAfterMultilineCondition, 'rubocop/cop/layout/empty_line_after_multiline_condition'
      autoload_cop :EmptyLineBetweenDefs, 'rubocop/cop/layout/empty_line_between_defs'
      autoload_cop :EmptyLinesAfterModuleInclusion, 'rubocop/cop/layout/empty_lines_after_module_inclusion'
      autoload_cop :EmptyLinesAroundAccessModifier, 'rubocop/cop/layout/empty_lines_around_access_modifier'
      autoload_cop :EmptyLinesAroundArguments, 'rubocop/cop/layout/empty_lines_around_arguments'
      autoload_cop :EmptyLinesAroundAttributeAccessor, 'rubocop/cop/layout/empty_lines_around_attribute_accessor'
      autoload_cop :EmptyLinesAroundBeginBody, 'rubocop/cop/layout/empty_lines_around_begin_body'
      autoload_cop :EmptyLinesAroundBlockBody, 'rubocop/cop/layout/empty_lines_around_block_body'
      autoload_cop :EmptyLinesAroundClassBody, 'rubocop/cop/layout/empty_lines_around_class_body'
      autoload_cop :EmptyLinesAroundExceptionHandlingKeywords, 'rubocop/cop/layout/empty_lines_around_exception_handling_keywords'
      autoload_cop :EmptyLinesAroundMethodBody, 'rubocop/cop/layout/empty_lines_around_method_body'
      autoload_cop :EmptyLinesAroundModuleBody, 'rubocop/cop/layout/empty_lines_around_module_body'
      autoload_cop :EmptyLines, 'rubocop/cop/layout/empty_lines'
      autoload_cop :EndAlignment, 'rubocop/cop/layout/end_alignment'
      autoload_cop :EndOfLine, 'rubocop/cop/layout/end_of_line'
      autoload_cop :ExtraSpacing, 'rubocop/cop/layout/extra_spacing'
      autoload_cop :FirstArgumentIndentation, 'rubocop/cop/layout/first_argument_indentation'
      autoload_cop :FirstArrayElementIndentation, 'rubocop/cop/layout/first_array_element_indentation'
      autoload_cop :FirstArrayElementLineBreak, 'rubocop/cop/layout/first_array_element_line_break'
      autoload_cop :FirstHashElementIndentation, 'rubocop/cop/layout/first_hash_element_indentation'
      autoload_cop :FirstHashElementLineBreak, 'rubocop/cop/layout/first_hash_element_line_break'
      autoload_cop :FirstMethodArgumentLineBreak, 'rubocop/cop/layout/first_method_argument_line_break'
      autoload_cop :FirstMethodParameterLineBreak, 'rubocop/cop/layout/first_method_parameter_line_break'
      autoload_cop :FirstParameterIndentation, 'rubocop/cop/layout/first_parameter_indentation'
      autoload_cop :HashAlignment, 'rubocop/cop/layout/hash_alignment'
      autoload_cop :HeredocArgumentClosingParenthesis, 'rubocop/cop/layout/heredoc_argument_closing_parenthesis'
      autoload_cop :HeredocIndentation, 'rubocop/cop/layout/heredoc_indentation'
      autoload_cop :IndentationConsistency, 'rubocop/cop/layout/indentation_consistency'
      autoload_cop :IndentationStyle, 'rubocop/cop/layout/indentation_style'
      autoload_cop :IndentationWidth, 'rubocop/cop/layout/indentation_width'
      autoload_cop :InitialIndentation, 'rubocop/cop/layout/initial_indentation'
      autoload_cop :LeadingCommentSpace, 'rubocop/cop/layout/leading_comment_space'
      autoload_cop :LeadingEmptyLines, 'rubocop/cop/layout/leading_empty_lines'
      autoload_cop :LineContinuationLeadingSpace, 'rubocop/cop/layout/line_continuation_leading_space'
      autoload_cop :LineContinuationSpacing, 'rubocop/cop/layout/line_continuation_spacing'
      autoload_cop :LineEndStringConcatenationIndentation, 'rubocop/cop/layout/line_end_string_concatenation_indentation'
      autoload_cop :LineLength, 'rubocop/cop/layout/line_length'
      autoload_cop :MultilineArrayBraceLayout, 'rubocop/cop/layout/multiline_array_brace_layout'
      autoload_cop :MultilineArrayLineBreaks, 'rubocop/cop/layout/multiline_array_line_breaks'
      autoload_cop :MultilineAssignmentLayout, 'rubocop/cop/layout/multiline_assignment_layout'
      autoload_cop :MultilineBlockLayout, 'rubocop/cop/layout/multiline_block_layout'
      autoload_cop :MultilineHashBraceLayout, 'rubocop/cop/layout/multiline_hash_brace_layout'
      autoload_cop :MultilineHashKeyLineBreaks, 'rubocop/cop/layout/multiline_hash_key_line_breaks'
      autoload_cop :MultilineMethodArgumentLineBreaks, 'rubocop/cop/layout/multiline_method_argument_line_breaks'
      autoload_cop :MultilineMethodCallBraceLayout, 'rubocop/cop/layout/multiline_method_call_brace_layout'
      autoload_cop :MultilineMethodCallIndentation, 'rubocop/cop/layout/multiline_method_call_indentation'
      autoload_cop :MultilineMethodDefinitionBraceLayout, 'rubocop/cop/layout/multiline_method_definition_brace_layout'
      autoload_cop :MultilineMethodParameterLineBreaks, 'rubocop/cop/layout/multiline_method_parameter_line_breaks'
      autoload_cop :MultilineOperationIndentation, 'rubocop/cop/layout/multiline_operation_indentation'
      autoload_cop :ParameterAlignment, 'rubocop/cop/layout/parameter_alignment'
      autoload_cop :RedundantLineBreak, 'rubocop/cop/layout/redundant_line_break'
      autoload_cop :RescueEnsureAlignment, 'rubocop/cop/layout/rescue_ensure_alignment'
      autoload_cop :SingleLineBlockChain, 'rubocop/cop/layout/single_line_block_chain'
      autoload_cop :SpaceAfterColon, 'rubocop/cop/layout/space_after_colon'
      autoload_cop :SpaceAfterComma, 'rubocop/cop/layout/space_after_comma'
      autoload_cop :SpaceAfterMethodName, 'rubocop/cop/layout/space_after_method_name'
      autoload_cop :SpaceAfterNot, 'rubocop/cop/layout/space_after_not'
      autoload_cop :SpaceAfterSemicolon, 'rubocop/cop/layout/space_after_semicolon'
      autoload_cop :SpaceAroundBlockParameters, 'rubocop/cop/layout/space_around_block_parameters'
      autoload_cop :SpaceAroundEqualsInParameterDefault, 'rubocop/cop/layout/space_around_equals_in_parameter_default'
      autoload_cop :SpaceAroundKeyword, 'rubocop/cop/layout/space_around_keyword'
      autoload_cop :SpaceAroundMethodCallOperator, 'rubocop/cop/layout/space_around_method_call_operator'
      autoload_cop :SpaceAroundOperators, 'rubocop/cop/layout/space_around_operators'
      autoload_cop :SpaceBeforeBlockBraces, 'rubocop/cop/layout/space_before_block_braces'
      autoload_cop :SpaceBeforeBrackets, 'rubocop/cop/layout/space_before_brackets'
      autoload_cop :SpaceBeforeComma, 'rubocop/cop/layout/space_before_comma'
      autoload_cop :SpaceBeforeComment, 'rubocop/cop/layout/space_before_comment'
      autoload_cop :SpaceBeforeFirstArg, 'rubocop/cop/layout/space_before_first_arg'
      autoload_cop :SpaceBeforeSemicolon, 'rubocop/cop/layout/space_before_semicolon'
      autoload_cop :SpaceInLambdaLiteral, 'rubocop/cop/layout/space_in_lambda_literal'
      autoload_cop :SpaceInsideArrayPercentLiteral, 'rubocop/cop/layout/space_inside_array_percent_literal'
      autoload_cop :SpaceInsideArrayLiteralBrackets, 'rubocop/cop/layout/space_inside_array_literal_brackets'
      autoload_cop :SpaceInsideBlockBraces, 'rubocop/cop/layout/space_inside_block_braces'
      autoload_cop :SpaceInsideHashLiteralBraces, 'rubocop/cop/layout/space_inside_hash_literal_braces'
      autoload_cop :SpaceInsideParens, 'rubocop/cop/layout/space_inside_parens'
      autoload_cop :SpaceInsidePercentLiteralDelimiters, 'rubocop/cop/layout/space_inside_percent_literal_delimiters'
      autoload_cop :SpaceInsideRangeLiteral, 'rubocop/cop/layout/space_inside_range_literal'
      autoload_cop :SpaceInsideReferenceBrackets, 'rubocop/cop/layout/space_inside_reference_brackets'
      autoload_cop :SpaceInsideStringInterpolation, 'rubocop/cop/layout/space_inside_string_interpolation'
      autoload_cop :TrailingEmptyLines, 'rubocop/cop/layout/trailing_empty_lines'
      autoload_cop :TrailingWhitespace, 'rubocop/cop/layout/trailing_whitespace'
    end
  end
end
