# frozen_string_literal: true

require 'English'

# fileutils is autoloaded by pathname,
# but must be explicitly loaded here for inclusion in `$LOADED_FEATURES`.
require 'fileutils'

before_us = $LOADED_FEATURES.dup
require 'rainbow'

require 'regexp_parser'
require 'set'
require 'stringio'
require 'unicode/display_width'

# we have to require RuboCop's version, before rubocop-ast's
require_relative 'rubocop/version'
require 'rubocop-ast'

require_relative 'rubocop/ast_aliases'
require_relative 'rubocop/ext/comment'
require_relative 'rubocop/ext/range'
require_relative 'rubocop/ext/regexp_node'
require_relative 'rubocop/ext/regexp_parser'

require_relative 'rubocop/core_ext/string'
require_relative 'rubocop/ext/processed_source'

require_relative 'rubocop/error'
require_relative 'rubocop/file_finder'
require_relative 'rubocop/file_patterns'
require_relative 'rubocop/name_similarity'
require_relative 'rubocop/path_util'
require_relative 'rubocop/platform'
require_relative 'rubocop/string_interpreter'
require_relative 'rubocop/util'
require_relative 'rubocop/warning'

# rubocop:disable Style/RequireOrder

require_relative 'rubocop/cop/util'
require_relative 'rubocop/cop/offense'
require_relative 'rubocop/cop/message_annotator'
require_relative 'rubocop/cop/ignored_node'
require_relative 'rubocop/cop/autocorrect_logic'
require_relative 'rubocop/cop/exclude_limit'
require_relative 'rubocop/cop/badge'
require_relative 'rubocop/cop/registry'
require_relative 'rubocop/cop/base'
require_relative 'rubocop/cop/cop'
require_relative 'rubocop/cop/commissioner'
require_relative 'rubocop/cop/documentation'
require_relative 'rubocop/cop/corrector'
require_relative 'rubocop/cop/force'
require_relative 'rubocop/cop/severity'
require_relative 'rubocop/cop/generator'
require_relative 'rubocop/cop/generator/configuration_injector'
require_relative 'rubocop/cop/generator/require_file_injector'
require_relative 'rubocop/magic_comment'

require_relative 'rubocop/cop/variable_force'
require_relative 'rubocop/cop/variable_force/branch'
require_relative 'rubocop/cop/variable_force/branchable'
require_relative 'rubocop/cop/variable_force/variable'
require_relative 'rubocop/cop/variable_force/assignment'
require_relative 'rubocop/cop/variable_force/reference'
require_relative 'rubocop/cop/variable_force/scope'
require_relative 'rubocop/cop/variable_force/variable_table'

require_relative 'rubocop/cop/utils/format_string'

require_relative 'rubocop/cop/bundler'
require_relative 'rubocop/cop/gemspec'
require_relative 'rubocop/cop/layout'
require_relative 'rubocop/cop/lint'
require_relative 'rubocop/cop/metrics'
require_relative 'rubocop/cop/migration'
require_relative 'rubocop/cop/naming'
require_relative 'rubocop/cop/style'
require_relative 'rubocop/cop/security'

require_relative 'rubocop/cop/team'
require_relative 'rubocop/formatter'

require_relative 'rubocop/cached_data'
require_relative 'rubocop/config'
require_relative 'rubocop/config_loader_resolver'
require_relative 'rubocop/config_loader'
require_relative 'rubocop/config_obsoletion/rule'
require_relative 'rubocop/config_obsoletion/cop_rule'
require_relative 'rubocop/config_obsoletion/parameter_rule'
require_relative 'rubocop/config_obsoletion/changed_enforced_styles'
require_relative 'rubocop/config_obsoletion/changed_parameter'
require_relative 'rubocop/config_obsoletion/extracted_cop'
require_relative 'rubocop/config_obsoletion/removed_cop'
require_relative 'rubocop/config_obsoletion/renamed_cop'
require_relative 'rubocop/config_obsoletion/split_cop'
require_relative 'rubocop/config_obsoletion'
require_relative 'rubocop/config_store'
require_relative 'rubocop/config_validator'
require_relative 'rubocop/feature_loader'
require_relative 'rubocop/lsp'
require_relative 'rubocop/target_finder'
require_relative 'rubocop/directive_comment'
require_relative 'rubocop/comment_config'
require_relative 'rubocop/result_cache'
require_relative 'rubocop/runner'
require_relative 'rubocop/cli'
require_relative 'rubocop/cli/command'
require_relative 'rubocop/cli/environment'
require_relative 'rubocop/cli/command/base'
require_relative 'rubocop/cli/command/auto_generate_config'
require_relative 'rubocop/cli/command/execute_runner'
require_relative 'rubocop/cli/command/init_dotfile'
require_relative 'rubocop/cli/command/lsp'
require_relative 'rubocop/cli/command/mcp'
require_relative 'rubocop/cli/command/show_cops'
require_relative 'rubocop/cli/command/show_docs_url'
require_relative 'rubocop/cli/command/suggest_extensions'
require_relative 'rubocop/cli/command/version'
require_relative 'rubocop/config_regeneration'
require_relative 'rubocop/options'
require_relative 'rubocop/target_ruby'
require_relative 'rubocop/yaml_duplication_checker'
require_relative 'rubocop/pending_cops_reporter'

# rubocop:enable Style/RequireOrder

unless File.exist?("#{__dir__}/../rubocop.gemspec") # Check if we are a gem
  RuboCop::ResultCache.rubocop_required_features = $LOADED_FEATURES - before_us
end
RuboCop::AST.rubocop_loaded if RuboCop::AST.respond_to?(:rubocop_loaded)

module RuboCop
  autoload :Lockfile, 'rubocop/lockfile'
  autoload :RemoteConfig, 'rubocop/remote_config'

  module Cop
    # mixins
    autoload :ArrayMinSize, 'rubocop/cop/mixin/array_min_size'
    autoload :ArraySyntax, 'rubocop/cop/mixin/array_syntax'
    autoload :Alignment, 'rubocop/cop/mixin/alignment'
    autoload :AllowedIdentifiers, 'rubocop/cop/mixin/allowed_identifiers'
    autoload :AllowedMethods, 'rubocop/cop/mixin/allowed_methods'
    autoload :AllowedPattern, 'rubocop/cop/mixin/allowed_pattern'
    autoload :AllowedReceivers, 'rubocop/cop/mixin/allowed_receivers'
    autoload :ForbiddenIdentifiers, 'rubocop/cop/mixin/forbidden_identifiers'
    autoload :ForbiddenPattern, 'rubocop/cop/mixin/forbidden_pattern'
    autoload :AutoCorrector, 'rubocop/cop/mixin/auto_corrector'
    autoload :CheckAssignment, 'rubocop/cop/mixin/check_assignment'
    autoload :CheckLineBreakable, 'rubocop/cop/mixin/check_line_breakable'
    autoload :CheckSingleLineSuitability, 'rubocop/cop/mixin/check_single_line_suitability'
    autoload :ConfigurableMax, 'rubocop/cop/mixin/configurable_max'
    autoload :CodeLength, 'rubocop/cop/mixin/code_length'
    autoload :ConfigurableEnforcedStyle, 'rubocop/cop/mixin/configurable_enforced_style'
    autoload :ConfigurableFormatting, 'rubocop/cop/mixin/configurable_formatting'
    autoload :ConfigurableNaming, 'rubocop/cop/mixin/configurable_naming'
    autoload :ConfigurableNumbering, 'rubocop/cop/mixin/configurable_numbering'
    autoload :DigHelp, 'rubocop/cop/mixin/dig_help'
    autoload :DocumentationComment, 'rubocop/cop/mixin/documentation_comment'
    autoload :Duplication, 'rubocop/cop/mixin/duplication'
    autoload :RangeHelp, 'rubocop/cop/mixin/range_help'
    autoload :AnnotationComment, 'rubocop/cop/mixin/annotation_comment'
    module Layout
      autoload :EmptyLinesAroundBody, 'rubocop/cop/mixin/empty_lines_around_body'
    end
    autoload :EmptyParameter, 'rubocop/cop/mixin/empty_parameter'
    autoload :EndKeywordAlignment, 'rubocop/cop/mixin/end_keyword_alignment'
    autoload :EndlessMethodRewriter, 'rubocop/cop/mixin/endless_method_rewriter'
    autoload :EnforceSuperclass, 'rubocop/cop/mixin/enforce_superclass'
    autoload :FirstElementLineBreak, 'rubocop/cop/mixin/first_element_line_break'
    autoload :FrozenStringLiteral, 'rubocop/cop/mixin/frozen_string_literal'
    autoload :GemDeclaration, 'rubocop/cop/mixin/gem_declaration'
    autoload :GemspecHelp, 'rubocop/cop/mixin/gemspec_help'
    autoload :HashAlignmentStyles, 'rubocop/cop/mixin/hash_alignment_styles'
    autoload :HashSubset, 'rubocop/cop/mixin/hash_subset'
    autoload :HashTransformMethod, 'rubocop/cop/mixin/hash_transform_method'
    autoload :IntegerNode, 'rubocop/cop/mixin/integer_node'
    autoload :Interpolation, 'rubocop/cop/mixin/interpolation'
    autoload :LineLengthHelp, 'rubocop/cop/mixin/line_length_help'
    autoload :MatchRange, 'rubocop/cop/mixin/match_range'
    autoload :HashShorthandSyntax, 'rubocop/cop/mixin/hash_shorthand_syntax'
    autoload :MethodComplexity, 'rubocop/cop/mixin/method_complexity'
    autoload :MethodPreference, 'rubocop/cop/mixin/method_preference'
    autoload :MinBodyLength, 'rubocop/cop/mixin/min_body_length'
    autoload :MinBranchesCount, 'rubocop/cop/mixin/min_branches_count'
    autoload :MultilineElementIndentation, 'rubocop/cop/mixin/multiline_element_indentation'
    autoload :MultilineElementLineBreaks, 'rubocop/cop/mixin/multiline_element_line_breaks'
    autoload :MultilineExpressionIndentation, 'rubocop/cop/mixin/multiline_expression_indentation'
    autoload :MultilineLiteralBraceLayout, 'rubocop/cop/mixin/multiline_literal_brace_layout'
    autoload :NegativeConditional, 'rubocop/cop/mixin/negative_conditional'
    autoload :Heredoc, 'rubocop/cop/mixin/heredoc'
    autoload :NilMethods, 'rubocop/cop/mixin/nil_methods'
    autoload :OnNormalIfUnless, 'rubocop/cop/mixin/on_normal_if_unless'
    autoload :OrderedGemNode, 'rubocop/cop/mixin/ordered_gem_node'
    autoload :Parentheses, 'rubocop/cop/mixin/parentheses'
    autoload :PercentArray, 'rubocop/cop/mixin/percent_array'
    autoload :PercentLiteral, 'rubocop/cop/mixin/percent_literal'
    autoload :PrecedingFollowingAlignment, 'rubocop/cop/mixin/preceding_following_alignment'
    autoload :PreferredDelimiters, 'rubocop/cop/mixin/preferred_delimiters'
    autoload :RationalLiteral, 'rubocop/cop/mixin/rational_literal'
    autoload :RequireLibrary, 'rubocop/cop/mixin/require_library'
    autoload :RescueNode, 'rubocop/cop/mixin/rescue_node'
    autoload :SafeAssignment, 'rubocop/cop/mixin/safe_assignment'
    autoload :SpaceAfterPunctuation, 'rubocop/cop/mixin/space_after_punctuation'
    autoload :SpaceBeforePunctuation, 'rubocop/cop/mixin/space_before_punctuation'
    autoload :SurroundingSpace, 'rubocop/cop/mixin/surrounding_space'
    autoload :StatementModifier, 'rubocop/cop/mixin/statement_modifier'
    autoload :StringHelp, 'rubocop/cop/mixin/string_help'
    autoload :StringLiteralsHelp, 'rubocop/cop/mixin/string_literals_help'
    autoload :SymbolHelp, 'rubocop/cop/mixin/symbol_help'
    autoload :TargetRubyVersion, 'rubocop/cop/mixin/target_ruby_version'
    autoload :TrailingBody, 'rubocop/cop/mixin/trailing_body'
    autoload :TrailingComma, 'rubocop/cop/mixin/trailing_comma'
    autoload :UncommunicativeName, 'rubocop/cop/mixin/uncommunicative_name'
    module Lint
      autoload :UnusedArgument, 'rubocop/cop/mixin/unused_argument'
    end
    autoload :VisibilityHelp, 'rubocop/cop/mixin/visibility_help'
    autoload :CommentsHelp, 'rubocop/cop/mixin/comments_help'
    autoload :DefNode, 'rubocop/cop/mixin/def_node'

    # correctors
    autoload :AlignmentCorrector, 'rubocop/cop/correctors/alignment_corrector'
    autoload :ConditionCorrector, 'rubocop/cop/correctors/condition_corrector'
    autoload :EachToForCorrector, 'rubocop/cop/correctors/each_to_for_corrector'
    autoload :EmptyLineCorrector, 'rubocop/cop/correctors/empty_line_corrector'
    autoload :ForToEachCorrector, 'rubocop/cop/correctors/for_to_each_corrector'
    autoload :IfThenCorrector, 'rubocop/cop/correctors/if_then_corrector'
    autoload :LambdaLiteralToMethodCorrector, 'rubocop/cop/correctors/lambda_literal_to_method_corrector'
    autoload :LineBreakCorrector, 'rubocop/cop/correctors/line_break_corrector'
    autoload :MultilineLiteralBraceCorrector, 'rubocop/cop/correctors/multiline_literal_brace_corrector'
    autoload :OrderedGemCorrector, 'rubocop/cop/correctors/ordered_gem_corrector'
    autoload :ParenthesesCorrector, 'rubocop/cop/correctors/parentheses_corrector'
    autoload :PercentLiteralCorrector, 'rubocop/cop/correctors/percent_literal_corrector'
    autoload :PunctuationCorrector, 'rubocop/cop/correctors/punctuation_corrector'
    autoload :RequireLibraryCorrector, 'rubocop/cop/correctors/require_library_corrector'
    autoload :SpaceCorrector, 'rubocop/cop/correctors/space_corrector'
    autoload :StringLiteralCorrector, 'rubocop/cop/correctors/string_literal_corrector'
    autoload :UnusedArgCorrector, 'rubocop/cop/correctors/unused_arg_corrector'
  end
end
